# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "text to output here" > /cygddrive/c/users/rajeev/temp/output.txt
      - persist_to_workspace:
          root: /cygdrive/c/users/rajeev/temp
          paths:
            - target/application.jar
            - build/*
  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: cat /cygdrive/c/users/rajeev/temp/output.txt
      - attach_workspace:
          at: /cygdrive/c/users/rajeev/temp/
workflows:
  welcome:
    jobs:
      - save_hello_world_output
      - print_output_file